CREATE TABLE `Station` (
  `StationID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `Name` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `Url` text DEFAULT NULL,
  `Homepage` text DEFAULT NULL,
  `Favicon` text DEFAULT NULL,
  `Creation` datetime NOT NULL,
  `Country` varchar(250) DEFAULT NULL,
  `Language` varchar(100) DEFAULT NULL,
  `Tags` text DEFAULT NULL,
  `Votes` int(11) DEFAULT 0,
  `Subcountry` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `clickcount` int(11) NOT NULL DEFAULT 0,
  `ClickTrend` int(11) DEFAULT 0,
  `ClickTimestamp` datetime DEFAULT NULL,
  `Codec` varchar(20) DEFAULT NULL,
  `LastCheckOK` tinyint(1) NOT NULL DEFAULT 1,
  `LastCheckTime` datetime DEFAULT NULL,
  `Bitrate` int(11) NOT NULL DEFAULT 0,
  `UrlCache` text NOT NULL,
  `LastCheckOkTime` datetime DEFAULT NULL,
  `Hls` tinyint(1) NOT NULL DEFAULT 0,
  `ChangeUuid` char(36) DEFAULT NULL,
  `StationUuid` char(36) DEFAULT NULL,
  `CountryCode` varchar(2) DEFAULT NULL,
  `LastLocalCheckTime` datetime DEFAULT NULL,
  `CountrySubdivisionCode` varchar(6) DEFAULT NULL,
  `GeoLat` double DEFAULT NULL,
  `GeoLong` double DEFAULT NULL,
  `SslError` tinyint(1) NOT NULL DEFAULT 0,
  `LanguageCodes` text DEFAULT NULL,
  `ExtendedInfo` tinyint(1) NOT NULL DEFAULT 0,
  `ServerUuid` char(36) DEFAULT NULL,
  PRIMARY KEY (`StationID`),
  UNIQUE KEY `ChangeUuid` (`ChangeUuid`),
  UNIQUE KEY `StationUuid` (`StationUuid`),
  KEY `FK_Station_StreamingServers` (`ServerUuid`),
  CONSTRAINT `FK_Station_StreamingServers` FOREIGN KEY (`ServerUuid`) REFERENCES `StreamingServers` (`Uuid`)
) ENGINE=InnoDB AUTO_INCREMENT=60483 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin