apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
//apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'kotlin-parcelize'

def getAvailableLocales() {
    def tree = fileTree(dir: 'src/main/res', include: '**/strings.xml')
    return tree.collect {
        def lang = it.getParentFile().getName() - "values-" - "values"
        lang = lang.replace("-r", "-")
        if (lang.empty) {
            lang = "en"
        }
        lang
    }
}

android {
    namespace 'net.ounben.AMARadio'
    compileSdkVersion 37

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        viewBinding true
        buildConfig true
        aidl true
    }

    defaultConfig {
        applicationId "ch.ounben.AMARadio"
        minSdkVersion 23
        targetSdkVersion 37

        versionCode 100
        versionName "0.93"

        vectorDrawables.useSupportLibrary = true

        ksp {
            arg("room.schemaLocation", "$projectDir/schemas".toString())
        }

        resValue 'string', 'app_name_untranslated', 'AMARadio'

        def escapedLocales = getAvailableLocales().collect { "\"" + it + "\"" }
        buildConfigField "String[]", "AVAILABLE_LOCALES", String.format("{ %s }", escapedLocales.join(","))

        buildConfigField "java.util.concurrent.atomic.AtomicBoolean", "IS_TESTING", "new java.util.concurrent.atomic.AtomicBoolean(false)"
    }


    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'

            lintOptions {
                disable 'MissingTranslation'
            }
        }
    }

    lint {
        abortOnError true
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()
        }
        animationsDisabled = true
        unitTests.returnDefaultValues = true
    }
}

// No longer needed, using version catalog


dependencies {
    implementation libs.androidx.media
    implementation libs.androidx.localbroadcastmanager
    implementation libs.androidx.viewpager
    implementation libs.androidx.drawerlayout
    implementation libs.androidx.swiperefreshlayout
    implementation libs.androidx.appcompat
    implementation libs.androidx.recyclerview
    implementation libs.material
    implementation libs.androidx.preference
    implementation libs.androidx.mediarouter
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.tvprovider

    implementation libs.okhttp
    implementation libs.gson
    implementation libs.coil

    implementation libs.androidx.media3.exoplayer
    implementation libs.androidx.media3.exoplayer.hls
    implementation libs.androidx.media3.ui
    implementation libs.androidx.media3.common

    implementation libs.java.string.similarity
    implementation libs.fuzzywuzzy

    implementation libs.androidx.room.runtime
    ksp libs.androidx.room.compiler
    implementation libs.androidx.room.ktx
    implementation libs.androidx.room.paging
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.kotlinx.coroutines.android

    implementation libs.androidx.paging.runtime

    // Google Cast & SafetyNet (Jetzt für alle Builds aktiv, da Flavors entfernt wurden)
    implementation libs.play.services.cast.framework
    // implementation 'com.google.android.gms:play-services-cast:21.2.0'
    implementation libs.play.services.cast.framework
    implementation libs.play.services.safetynet

    testImplementation libs.junit
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.vintage.engine
    testRuntimeOnly libs.junit.platform.launcher
}

android.applicationVariants.all { variant ->
    variant.outputs.all { output ->
        def appName = variant.mergedFlavor.resValues.get('string/app_name_untranslated').getValue()
        appName = "${appName}"

        appName += "-${variant.buildType.name}"

        if (variant.buildType.name == "debug") {
            appName += "-DEV"
        }

        def gitHash = { ->
            def stdout = new ByteArrayOutputStream()
            try {
                exec {
                    commandLine 'git', 'rev-parse', '--short', 'HEAD'
                    standardOutput = stdout
                }
                return stdout.toString().trim()
            } catch (Exception ignored) {
                return "No commit hash"
            }
        }

        resValue 'string', 'GIT_HASH', gitHash()

        def getBuildDate = {
            new Date().format('yyyy-MM-dd HH:mm:ss')
        }

        resValue 'string', 'BUILD_DATE', getBuildDate()

        def finalName = appName

        if (!versionName.isEmpty()) {
            finalName += "-" + versionName
        }

        finalName += "-" + gitHash() + ".apk"
        outputFileName = finalName
    }
}